In [1]:
import torch
import numpy as np
import time
import threading
import RL_ 
import gym
import gclib

In [2]:
g = gclib.py()
c = g.GCommand
g.GOpen("192.168.255.200 --direct -s ALL")
env=gym.make("RL_/CustomEnv-v0")

env.reset()

c:\Users\PIVUSER\Desktop\RL_VerticalAxisTurbine\Carousel\load_mat.py:36: DeprecationWarning: Please use `mat_struct` from the `scipy.io.matlab` namespace, the `scipy.io.matlab.mio5_params` namespace is deprecated.
  if isinstance(d[key], spio.matlab.mio5_params.mat_struct):
c:\Users\PIVUSER\miniconda3\envs\cloned_rl\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


192.168.255.200, DMC4080 Rev 1.2b, 10744
init
first episode


c:\Users\PIVUSER\miniconda3\envs\cloned_rl\lib\site-packages\gym\spaces\box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


Starting motor E
waiting for 3 periods
[[-1.54179679 -1.53939679  1.02530321  1.02590321  1.02960321]
 [-1.53449679 -1.53389679  1.02770321  1.02770321  1.02710321]
 [-1.53999679 -1.53449679  1.02650321  1.03140321  1.02590321]
 [-1.55949679 -1.54309679  1.02590321  1.02590321  1.02650321]
 [-1.53449679 -1.53759679  1.03140321  1.02650321  1.02650321]
 [-1.54179679 -1.53329679  1.02830321  1.02710321  1.02650321]
 [-1.54249679 -1.54179679  1.02650321  1.02710321  1.02590321]
 [-1.54119679 -1.55469679  1.02710321  1.02590321  1.02650321]
 [-1.53569679 -1.54119679  1.02710321  1.02710321  1.02650321]
 [-1.54309679 -1.54249679  1.02530321  1.03140321  1.02590321]
 [-1.53819679 -1.54059679  1.02650321  1.02650321  1.02960321]]
[[  -1.53449679   -1.53389679    1.02770321    1.02770321    1.02710321]
 [  -1.53999679   -1.53449679    1.02650321    1.03140321    1.02590321]
 [  -1.55949679   -1.54309679    1.02590321    1.02590321    1.02650321]
 [  -1.53449679   -1.53759679    1.03140321    1

c:\Users\PIVUSER\Desktop\RL_VerticalAxisTurbine\Carousel\RL_\envs\CustomEnv.py:438: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if window == np.ones((ws,5)) * med:


array([-0.555535  , -0.61098218,  0.        ])

In [6]:
def continuously_read():
    t=time.time()
    while time.time()-t<5:
        env.read_state()

In [8]:
env.history_states

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
env.i

0

In [10]:
daemon=threading.Thread(target=continuously_read,daemon=True,name="state_reader")

In [11]:

ti=time.time()
daemon.start()
while time.time()-ti<2:
    print(time.time())
    time.sleep(0.2)
print(env.history_states)

Exception in thread state_reader:
Traceback (most recent call last):
  File "c:\Users\PIVUSER\miniconda3\envs\cloned_rl\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "c:\Users\PIVUSER\miniconda3\envs\cloned_rl\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\PIVUSER\AppData\Local\Temp\ipykernel_21608\342840797.py", line 4, in continuously_read
  File "c:\Users\PIVUSER\Desktop\RL_VerticalAxisTurbine\Carousel\RL_\envs\CustomEnv.py", line 246, in read_state
    galil_output = list(map(float,(c("MG @AN[1],@AN[2],@AN[3],@AN[5],@AN[7],_TPE,_TDF,_TPF")).split()))
  File "c:\Users\PIVUSER\miniconda3\envs\cloned_rl\lib\site-packages\gclib.py", line 181, in GCommand
    _rc(_gclib.GCommand(self._gcon, c_command, self._buf, _buf_size, None))
OSError: exception: access violation reading 0x0000000000000000


1687187958.6834886
1687187958.8972828
1687187959.0982401
1687187959.3022468
1687187959.5053313
1687187959.7201014
1687187959.921171
1687187960.1219049
1687187960.3242397
1687187960.5260296
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
 list(map(float,(c("MG @AN[1],@AN[2],@AN[3],@AN[5],@AN[7],_TPE,_TDF,_TPF")).split()))

[2.5653, 2.5769, -0.0018, 0.0, -0.0006, 0.0, 52.0, 0.0]